### ISSUE TITLE
Convert project to NPM package

### ISSUE THREAD

**Issue by timobrembeck** [PokemonGoers/PokeMap-2#16]
Create a client side API  as described here: https://github.com/PokemonGoers/Catch-em-all/issues/9
- Define which options the map expects at initialization
- Provide methods for @PokemonGoers/catch-em-all  that they can call when they need the map to do something, e.g. go to a specific location `pokeMap.goTo({ longitude, latitude })` (or zoom in/out)
- Trigger events to which they can listen to when their UI should display something,  e.g. `pokeMap.on('clickedPokemon', (pokemon) => { ourUI.doSomething(pokemon) })`

**Comment by sacdallago** [comment]
The word API scared me for a moment :D
In other words: a set of event listeners and functions to interact with the tool, right? Not the http://../something type of API?
Just making it 400% clear :)

**Comment by timobrembeck** [comment]
Yes, I just used the word choice of the discussion in the other issue without thinking of a better term.
Do you think this idea is useful, or would you rather recommend the continuation of the current work (we as map team also doing parts of the UI)?

**Comment by gyachdav** [comment]
Yes this is the right path you should be following - clearly define how wrappers and/or external tools interact with your app. 

Just make it also known on your README.md or your (even better) on your repo's wiki.

**Comment by MajorBreakfast** [comment]
Hey guys,

we, the UI team AKA Project E, had a very productive team meeting yesterday in which we created an app storyboard with all screens of the app.

Now it is somewhat clear for us what we need. I'm going to write down all the API features until this evening and then publish it as a first draft of the API. Then it will be feedback time :) I'll post a link in this issue here once it's ready.

SPOILER: Since all Pokemon data will flow through this API, it will also include functionality that is not directly map related. However, for you that will mean just a few additional JSON API calls.

**Comment by sacdallago** [comment]
@MajorBreakfast you are mixing concerns, exactly what I was fearing. The API you refer to is @PokemonGoers/pokedata

**Comment by MajorBreakfast** [comment]
@sacdallago Hmm I see what you mean. I think the proposed JS API draft will be good. I'm going to talk to project A about it.

**Comment by MajorBreakfast** [comment]
PokeData JS API draft https://github.com/PokemonGoers/Catch-em-all/issues/23
PokeMap JS API draft https://github.com/PokemonGoers/Catch-em-all/issues/24 (between our teams)

**Comment by johartl** [comment]
I would like to push this topic again. Right now, we're requiring your package from your github repository directly.

``` (javascript)
// package.json
{
  "dependencies": {
    "pokemap-2": "github:pokemongoers/PokeMap-2#develop",
  }
}
```

It would be really important that you publish your package on npm. Also, your code uses ES6 syntax and you should probably transpile your code to ES5 JavaScript before publishing it. For instance, after having integrated your map some of our test cases fail because they are run on Travis which uses an older version of Chromium that does not support ES6 yet. 

So the important steps are
- [x] Set up a build step including transpilation from ES6 to ES5 sources
- [x] Publish your package on npm
- [ ] Introduce some versioning scheme for your package and upload stable releases to npm

**Comment by johartl** [comment]
What's the status on releasing your code as npm package?
Btw, the ES6 to ES5 transpiling step was implemented in #37 so I checked that item off the list.

**Comment by farisca** [comment]
The package is available under the name pokemap-2 (https://www.npmjs.com/package/pokemap-2)

**Comment by johartl** [comment]
Great! I just tried it out and `npm install pokemap-2` fails because of unmet dependencies:
- `browserify` is registered only in `devDependencies` but not in `dependencies`. However, this was already addressed by PR #42. So you just need to repackage the develop branch.
- `leaflet-routing-machine` and `leaflet-control-geocoder` are missing entirely. I added this to the comments for #43.

It would be good if you could tag your branches from now on and use the same versioning scheme in your package.json. I had a hard time trying to figure out which commit you actually pushed to npm (I assumed it was the develop branch).

**Comment by sacdallago** [comment]
Any newwwwws? I have some: last two days of
![](https://lh3.googleusercontent.com/rADORGMBsFf3p9KY0dWVgQXL-bD8SIS8VUh9vfZXOemdLTLAD8jypMpndX3KABQPo5GgxktPaI13dHxYBarm02BrwBanEr9tJIQ1rOU9rIPwS7I_TgqZdEeF4t05MWPTl0hXXmhltxwllchESdrJDEssUSQxcAQHckkcv44kP8MNEokKMPrQihztxipGGk159QUVJeWuGR6l4rkK4UlH2vriNx-dcoAp_pclbkYORLPA-la6dKgCtlWpslYXKGXNnZRLLJpkQA7DL7bEzq3k96VCVePM-NmjMTmEapXZ7Jb3KdvIAvGrwXtZL9cv0rkiCnRPySKAvGj7qhAJ5tGZN7VZf6i5T7Eo6jNFUYXS07aqQr72BjQQHABUSEz6ffHnCcV2Qha26b2P_h8J6ble6lU2zgHySPIzuL7hZzIyGNiwvOiM8cb-DxGgTe1VZDIpGXBZKUy1sbaRm3oSRYfoY2BbgAT3fWVZujkFjSJ1eTdeqaUnZfVAxOFFkwb7d-toAwF7_C-GPrVccZ_joBjpLkcnAs4NvVIZnYmuQZ-UUrmLgPpjZrHnlI9gnL3ii1Anz1HvyxA_3id6Oe33Tye-5d_3OhZ9zzPpgrUcvD8I12jgcwRrCg=w615-h346-no)

and then I'm gonna be fully back 😈

**Comment by WoH** [comment]
https://www.npmjs.com/package/pokemap-2
